#appveyor.yml reference: http://www.appveyor.com/docs/appveyor-yml
#online YAML parser: http://yaml-online-parser.appspot.com/

version: 0.4.{build}

branches:
  except:
    - master

os: Windows Server 2012

build:
  project: Pulsar4X/Pulsar4X.sln